### ISSUE TITLE
Need to rewrite this line into relative path

### ISSUE THREAD

**Issue by rdbz** [TheRealBarenziah/jdr9000#1]
Hey, there is an issue here :
https://github.com/TheRealBarenziah/jdr9000/blob/909bce093f4b1bc1250c03f0ea4e8b95414f18ae/commands/snap.js#L8

Would love to see this working on my setup :)

**Comment by TheRealBarenziah** [comment]
Hello, thank you for noticing this! [This](https://github.com/TheRealBarenziah/jdr9000/commit/902dae7c9b29e80280ce29b25125eef2b2ee1c86#diff-188b412a89e25dbcf77fbf93c8cbc11fR11) should fix it.

Feel free to reopen this issue if it doesn't :)
